### ISSUE TITLE
Setting-up instructions on README

### ISSUE THREAD

**Issue by avisionh** [ukgovdatascience/govcookiecutter#19]
> *"As a new user of cookiecutter, I need a step-by-step walkthrough on the `README.md` that outlines how I can set-up the pre-commit framework and secrets management. This is so I can benefit from these features when I create a new project. I need it in the `README.md` because this is the most intuitive place I will find such instructions."*

Flag in the `README.md` files the instructions you need to set-up this framework for projects, especially with respect to:

1. installing python
1. create a python virtual environment
1. `git init`
1. `make requirements`

**Comment by avisionh** [comment]
Has been flagged by:
- @nacnudus - https://github.com/ukgovdatascience/govcookiecutter/pull/16#pullrequestreview-591192820
- @exfalsoquodlibet - https://github.com/ukgovdatascience/govcookiecutter/pull/16#pullrequestreview-592029939

**Comment by ESKYoung** [comment]
Closing this issue, as it's been fixed in #16 AFAIK!
