### ISSUE TITLE
Implement Poetry in the repository

### ISSUE THREAD

**Issue by ESKYoung** [ukgovdatascience/govcookiecutter#32]
To better handle dependency management, I'm suggesting we switch to [Poetry](https://python-poetry.org/).

This will be a breaking change for users, as they can currently chose how they install packages, but it'll bring many other improvements including easier publication of packages to PyPI, easier resolution of outdated dependencies, local installation of the `src` package (this will need renaming).

Thoughts welcome!

**Comment by ntoll** [comment]
Please don't do this. :wink: 

The `requirements.txt` "standard" remains the most common way to do package management, and while `poetry` is cool it is nowhere near a standard. Given the vagaries of Python packaging, there is no guarantee `poetry` will become a long term and standard "thing" unless it becomes a part of the core Python workflow or it is in some way blessed by the [PyPA](https://www.pypa.io/en/latest/) (Python Packaging Authority). For what it's worth, `requirements.txt` [is blessed by the PyPA](https://pip.pypa.io/en/stable/user_guide/#requirements-files).

Should they decide to bless one tool over another, perhaps revisit this template and revise to the official advice from the Python core team. :+1:

**Comment by ESKYoung** [comment]
Thanks @ntoll for the useful comments! Much appreciated! I've also had some offline discussions with @maxf and @exfalsoquodlibet, who are all in agreement with you. We could add Poetry (and others such as Pipenv) as _options_ rather than mandating a choice, but I'll leave that for others to contribute!

Closing this issue - thanks again for your thoughts!
